AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - vendor/**/*
    - db/**/*
    - bin/**/*
    - lib/tasks/*
    - config/**/*

Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - config/routes.rb
Style/ClassAndModuleChildren:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Metrics/AbcSize:
  Enabled: true
  Max: 16
Naming/PredicateName:
  Enabled: false